// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqcLPZ5ice6vGWDqFf3wC3JETEdTL2Ks',
    appId: '1:232386619681:web:459560da6873d063c4f660',
    messagingSenderId: '232386619681',
    projectId: 'medicine-dispenser-app',
    authDomain: 'medicine-dispenser-app.firebaseapp.com',
    databaseURL: 'https://medicine-dispenser-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-app.firebasestorage.app',
    measurementId: 'G-49QD20YN56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeW1YzFY9i2BuGBCEHCR-H0sDecX0Bjw4',
    appId: '1:232386619681:android:59f93229288cd4ccc4f660',
    messagingSenderId: '232386619681',
    projectId: 'medicine-dispenser-app',
    databaseURL: 'https://medicine-dispenser-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2lHcJIdKI6P1u4QqKXjCIgGp6Zzo7Kuw',
    appId: '1:232386619681:ios:594e0733fd22a27dc4f660',
    messagingSenderId: '232386619681',
    projectId: 'medicine-dispenser-app',
    databaseURL: 'https://medicine-dispenser-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-app.firebasestorage.app',
    iosBundleId: 'com.example.medicineDispenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2lHcJIdKI6P1u4QqKXjCIgGp6Zzo7Kuw',
    appId: '1:232386619681:ios:594e0733fd22a27dc4f660',
    messagingSenderId: '232386619681',
    projectId: 'medicine-dispenser-app',
    databaseURL: 'https://medicine-dispenser-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-app.firebasestorage.app',
    iosBundleId: 'com.example.medicineDispenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqcLPZ5ice6vGWDqFf3wC3JETEdTL2Ks',
    appId: '1:232386619681:web:415c0e09c9eb438fc4f660',
    messagingSenderId: '232386619681',
    projectId: 'medicine-dispenser-app',
    authDomain: 'medicine-dispenser-app.firebaseapp.com',
    databaseURL: 'https://medicine-dispenser-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-dispenser-app.firebasestorage.app',
    measurementId: 'G-63MYBTZ9DL',
  );
}
